### ISSUE TITLE
Installation Process is a pain in the ass.

### ISSUE THREAD

**Issue by asimulined** [astrealRBLX/RoUI3#2]
Please make a tutorial on how to setup ROUI3 on Visual Studio Code.

**Comment by astrealRBLX** [comment]
I don't think this needs a tutorial. If it's for contribution purposes someone with basic experience should be able to set it up themselves very easily. If it's for compilation/installation purposes then going in-depth on how to compile it defeats the purpose of the store page for the plugin.
